[2025-05-21T09:21:22.559+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-21T09:21:22.612+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: merge_sources_pipeline.prediction manual__2025-05-21T09:20:57.597132+00:00 [queued]>
[2025-05-21T09:21:22.633+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: merge_sources_pipeline.prediction manual__2025-05-21T09:20:57.597132+00:00 [queued]>
[2025-05-21T09:21:22.634+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-05-21T09:21:22.658+0000] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): prediction> on 2025-05-21 09:20:57.597132+00:00
[2025-05-21T09:21:22.679+0000] {standard_task_runner.py:72} INFO - Started process 782 to run task
[2025-05-21T09:21:22.688+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'merge_sources_pipeline', 'prediction', 'manual__2025-05-21T09:20:57.597132+00:00', '--job-id', '97', '--raw', '--subdir', 'DAGS_FOLDER/inference_dag.py', '--cfg-path', '/tmp/tmp522zh4cx']
[2025-05-21T09:21:22.694+0000] {standard_task_runner.py:105} INFO - Job 97: Subtask prediction
[2025-05-21T09:21:22.797+0000] {task_command.py:467} INFO - Running <TaskInstance: merge_sources_pipeline.prediction manual__2025-05-21T09:20:57.597132+00:00 [running]> on host c735ccec6410
[2025-05-21T09:21:22.974+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='merge_sources_pipeline' AIRFLOW_CTX_TASK_ID='prediction' AIRFLOW_CTX_EXECUTION_DATE='2025-05-21T09:20:57.597132+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-21T09:20:57.597132+00:00'
[2025-05-21T09:21:22.976+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-05-21T09:21:23.037+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/inference_dag.py", line 96, in prediction
    result_df = run_inference(preprocessed_df)
  File "/opt/airflow/scripts/inference.py", line 16, in run_inference
    y_pred = predictor.predict_contrails(df_predict)
  File "/opt/airflow/scripts/predictor.py", line 33, in predict_contrails
    return self.model.predict(df)
  File "/home/airflow/.local/lib/python3.10/site-packages/xgboost/core.py", line 729, in inner_f
    return func(**kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/xgboost/sklearn.py", line 1327, in predict
    predts = self.get_booster().inplace_predict(
  File "/home/airflow/.local/lib/python3.10/site-packages/xgboost/core.py", line 729, in inner_f
    return func(**kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/xgboost/core.py", line 2667, in inplace_predict
    self._validate_features(fns)
  File "/home/airflow/.local/lib/python3.10/site-packages/xgboost/core.py", line 3243, in _validate_features
    raise ValueError(msg.format(self.feature_names, feature_names))
ValueError: feature_names mismatch: ['Aircraft', 'Engine', 'Seats', 'Origin Airport', 'Destination Airport', 'Distance Flown (km)', 'CO2 (kgCO2e)', 'Month', 'Day', 'Weekday', 'Takeoff_Hour'] []
expected Aircraft, Takeoff_Hour, Destination Airport, Origin Airport, CO2 (kgCO2e), Month, Weekday, Distance Flown (km), Day, Engine, Seats in input data
[2025-05-21T09:21:23.076+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=merge_sources_pipeline, task_id=prediction, run_id=manual__2025-05-21T09:20:57.597132+00:00, execution_date=20250521T092057, start_date=20250521T092122, end_date=20250521T092123
[2025-05-21T09:21:23.149+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-05-21T09:21:23.150+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 97 for task prediction (feature_names mismatch: ['Aircraft', 'Engine', 'Seats', 'Origin Airport', 'Destination Airport', 'Distance Flown (km)', 'CO2 (kgCO2e)', 'Month', 'Day', 'Weekday', 'Takeoff_Hour'] []
expected Aircraft, Takeoff_Hour, Destination Airport, Origin Airport, CO2 (kgCO2e), Month, Weekday, Distance Flown (km), Day, Engine, Seats in input data; 782)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/inference_dag.py", line 96, in prediction
    result_df = run_inference(preprocessed_df)
  File "/opt/airflow/scripts/inference.py", line 16, in run_inference
    y_pred = predictor.predict_contrails(df_predict)
  File "/opt/airflow/scripts/predictor.py", line 33, in predict_contrails
    return self.model.predict(df)
  File "/home/airflow/.local/lib/python3.10/site-packages/xgboost/core.py", line 729, in inner_f
    return func(**kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/xgboost/sklearn.py", line 1327, in predict
    predts = self.get_booster().inplace_predict(
  File "/home/airflow/.local/lib/python3.10/site-packages/xgboost/core.py", line 729, in inner_f
    return func(**kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/xgboost/core.py", line 2667, in inplace_predict
    self._validate_features(fns)
  File "/home/airflow/.local/lib/python3.10/site-packages/xgboost/core.py", line 3243, in _validate_features
    raise ValueError(msg.format(self.feature_names, feature_names))
ValueError: feature_names mismatch: ['Aircraft', 'Engine', 'Seats', 'Origin Airport', 'Destination Airport', 'Distance Flown (km)', 'CO2 (kgCO2e)', 'Month', 'Day', 'Weekday', 'Takeoff_Hour'] []
expected Aircraft, Takeoff_Hour, Destination Airport, Origin Airport, CO2 (kgCO2e), Month, Weekday, Distance Flown (km), Day, Engine, Seats in input data
[2025-05-21T09:21:23.184+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-05-21T09:21:23.235+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-21T09:21:23.239+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
