[2025-05-20T16:54:54.732+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-20T16:54:54.781+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: merge_sources_pipeline.run_merge manual__2025-05-20T16:54:46.896323+00:00 [queued]>
[2025-05-20T16:54:54.805+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: merge_sources_pipeline.run_merge manual__2025-05-20T16:54:46.896323+00:00 [queued]>
[2025-05-20T16:54:54.805+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-05-20T16:54:54.831+0000] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): run_merge> on 2025-05-20 16:54:46.896323+00:00
[2025-05-20T16:54:54.851+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1281) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-20T16:54:54.855+0000] {standard_task_runner.py:72} INFO - Started process 1283 to run task
[2025-05-20T16:54:54.855+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'merge_sources_pipeline', 'run_merge', 'manual__2025-05-20T16:54:46.896323+00:00', '--job-id', '66', '--raw', '--subdir', 'DAGS_FOLDER/inference_dag.py', '--cfg-path', '/tmp/tmp7g3rtvsp']
[2025-05-20T16:54:54.861+0000] {standard_task_runner.py:105} INFO - Job 66: Subtask run_merge
[2025-05-20T16:54:54.963+0000] {task_command.py:467} INFO - Running <TaskInstance: merge_sources_pipeline.run_merge manual__2025-05-20T16:54:46.896323+00:00 [running]> on host e9df7b98481e
[2025-05-20T16:54:55.902+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='merge_sources_pipeline' AIRFLOW_CTX_TASK_ID='run_merge' AIRFLOW_CTX_EXECUTION_DATE='2025-05-20T16:54:46.896323+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-20T16:54:46.896323+00:00'
[2025-05-20T16:54:55.904+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-05-20T16:54:55.961+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-05-20T16:54:55.982+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-05-20T16:54:55.983+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=merge_sources_pipeline, task_id=run_merge, run_id=manual__2025-05-20T16:54:46.896323+00:00, execution_date=20250520T165446, start_date=20250520T165454, end_date=20250520T165455
[2025-05-20T16:54:56.081+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-05-20T16:54:56.115+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-20T16:54:56.118+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
