[2025-05-21T10:07:58.843+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-21T10:07:58.885+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: merge_sources_pipeline.wait_for_aircraft_file manual__2025-05-21T10:07:54.939654+00:00 [queued]>
[2025-05-21T10:07:58.905+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: merge_sources_pipeline.wait_for_aircraft_file manual__2025-05-21T10:07:54.939654+00:00 [queued]>
[2025-05-21T10:07:58.906+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-05-21T10:07:58.935+0000] {taskinstance.py:2890} INFO - Executing <Task(FileSensor): wait_for_aircraft_file> on 2025-05-21 10:07:54.939654+00:00
[2025-05-21T10:07:58.962+0000] {standard_task_runner.py:72} INFO - Started process 1476 to run task
[2025-05-21T10:07:58.972+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'merge_sources_pipeline', 'wait_for_aircraft_file', 'manual__2025-05-21T10:07:54.939654+00:00', '--job-id', '109', '--raw', '--subdir', 'DAGS_FOLDER/inference_dag.py', '--cfg-path', '/tmp/tmp91cs6u16']
[2025-05-21T10:07:58.980+0000] {standard_task_runner.py:105} INFO - Job 109: Subtask wait_for_aircraft_file
[2025-05-21T10:07:59.116+0000] {task_command.py:467} INFO - Running <TaskInstance: merge_sources_pipeline.wait_for_aircraft_file manual__2025-05-21T10:07:54.939654+00:00 [running]> on host c735ccec6410
[2025-05-21T10:07:59.294+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='merge_sources_pipeline' AIRFLOW_CTX_TASK_ID='wait_for_aircraft_file' AIRFLOW_CTX_EXECUTION_DATE='2025-05-21T10:07:54.939654+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-21T10:07:54.939654+00:00'
[2025-05-21T10:07:59.298+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-05-21T10:07:59.305+0000] {baseoperator.py:423} WARNING - FileSensor.execute cannot be called outside TaskInstance!
[2025-05-21T10:07:59.358+0000] {base.py:84} INFO - Retrieving connection 'fs_default'
[2025-05-21T10:07:59.359+0000] {filesystem.py:109} INFO - Poking for file /opt/***/data/raw_data/aircraft_2025_05.csv
[2025-05-21T10:07:59.361+0000] {filesystem.py:113} INFO - Found File /opt/***/data/raw_data/aircraft_2025_05.csv last modified: 20250521001736
[2025-05-21T10:07:59.365+0000] {base.py:339} INFO - Success criteria met. Exiting.
[2025-05-21T10:07:59.366+0000] {filesystem.py:109} INFO - Poking for file /opt/***/data/raw_data/aircraft_2025_05.csv
[2025-05-21T10:07:59.367+0000] {filesystem.py:113} INFO - Found File /opt/***/data/raw_data/aircraft_2025_05.csv last modified: 20250521001736
[2025-05-21T10:07:59.388+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-05-21T10:07:59.389+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=merge_sources_pipeline, task_id=wait_for_aircraft_file, run_id=manual__2025-05-21T10:07:54.939654+00:00, execution_date=20250521T100754, start_date=20250521T100758, end_date=20250521T100759
[2025-05-21T10:07:59.517+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-05-21T10:07:59.592+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-05-21T10:07:59.596+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
