[2025-05-21T10:10:32.035+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-21T10:10:32.084+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: merge_sources_pipeline.wait_for_aircraft_file manual__2025-05-21T10:10:27.021421+00:00 [queued]>
[2025-05-21T10:10:32.109+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: merge_sources_pipeline.wait_for_aircraft_file manual__2025-05-21T10:10:27.021421+00:00 [queued]>
[2025-05-21T10:10:32.110+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-05-21T10:10:32.151+0000] {taskinstance.py:2890} INFO - Executing <Task(FileSensor): wait_for_aircraft_file> on 2025-05-21 10:10:27.021421+00:00
[2025-05-21T10:10:32.180+0000] {standard_task_runner.py:72} INFO - Started process 1581 to run task
[2025-05-21T10:10:32.193+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'merge_sources_pipeline', 'wait_for_aircraft_file', 'manual__2025-05-21T10:10:27.021421+00:00', '--job-id', '120', '--raw', '--subdir', 'DAGS_FOLDER/inference_dag.py', '--cfg-path', '/tmp/tmp28z8_dll']
[2025-05-21T10:10:32.201+0000] {standard_task_runner.py:105} INFO - Job 120: Subtask wait_for_aircraft_file
[2025-05-21T10:10:32.317+0000] {task_command.py:467} INFO - Running <TaskInstance: merge_sources_pipeline.wait_for_aircraft_file manual__2025-05-21T10:10:27.021421+00:00 [running]> on host c735ccec6410
[2025-05-21T10:10:32.489+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='merge_sources_pipeline' AIRFLOW_CTX_TASK_ID='wait_for_aircraft_file' AIRFLOW_CTX_EXECUTION_DATE='2025-05-21T10:10:27.021421+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-21T10:10:27.021421+00:00'
[2025-05-21T10:10:32.493+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-05-21T10:10:32.497+0000] {baseoperator.py:423} WARNING - FileSensor.execute cannot be called outside TaskInstance!
[2025-05-21T10:10:32.535+0000] {base.py:84} INFO - Retrieving connection 'fs_default'
[2025-05-21T10:10:32.537+0000] {filesystem.py:109} INFO - Poking for file /opt/***/data/raw_data/aircraft_2025_05.csv
[2025-05-21T10:10:32.538+0000] {filesystem.py:113} INFO - Found File /opt/***/data/raw_data/aircraft_2025_05.csv last modified: 20250521101018
[2025-05-21T10:10:32.538+0000] {base.py:339} INFO - Success criteria met. Exiting.
[2025-05-21T10:10:32.539+0000] {filesystem.py:109} INFO - Poking for file /opt/***/data/raw_data/aircraft_2025_05.csv
[2025-05-21T10:10:32.539+0000] {filesystem.py:113} INFO - Found File /opt/***/data/raw_data/aircraft_2025_05.csv last modified: 20250521101018
[2025-05-21T10:10:32.560+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-05-21T10:10:32.561+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=merge_sources_pipeline, task_id=wait_for_aircraft_file, run_id=manual__2025-05-21T10:10:27.021421+00:00, execution_date=20250521T101027, start_date=20250521T101032, end_date=20250521T101032
[2025-05-21T10:10:32.659+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-05-21T10:10:32.686+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
